version: "3"
services:
  ### postgres image
  postgres:
    image: postgres:latest
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
  ### postgres admin image
  postgres_admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
  ## application image
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword
    ports:
      - "8080:3100"